### ISSUE TITLE
[Insight] Text files should end with a newline character - in .travis.yml, line 16

### ISSUE THREAD

**Issue by meyerbaptiste** [coopTilleuls/CoopTilleulsYmlpBundle#9]
**[in .travis.yml, line 16](https://github.com/coopTilleuls/CoopTilleulsYmlpBundle/blob/master/.travis.yml#L16)**

> This file ends with no newline character. It won't render properly on a terminal, and it's considered a bad practice. Add a simple line feed as the last character to fix it.

```

script: vendor/bin/phpspec run

matrix:
  allow_failures:
    - php: hhvm
```

---

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/5be76419-0b77-4283-82c9-7333dcf43595/analyses/3)_
